### ISSUE TITLE
DMOJ problem list page on mobile UI issues

### ISSUE THREAD

**Issue by xiaowuc1** [DMOJ/online-judge#1055]
Reproduction link: https://dmoj.ca/problems/?show_types=1&type=3&page=8

Courtesy of @WallE256 - https://imgur.com/a/bezoX5q

**Comment by Ninjaclasher** [comment]
It seems that this issue does not happen if [some of the columns aren't purposely hidden](https://github.com/DMOJ/online-judge/blob/master/resources/problem.scss#L234). This might be fixing the symptoms rather than the problem, though.
