### ISSUE TITLE
Custom contest problem labels

### ISSUE THREAD

**Issue by Xyene** [DMOJ/online-judge#1124]
Right now we hardcode "1", "2", "3", etc. Some contests (like ICPC) may wish to use different labels, like "A", "B", or "C". I'm in favour of allowing user to override by a `label` field in `ContestProblem`, and give the contest format the choice when that is null by some sort of `get_label_for_problem(n : int) -> str` function.

**Comment by quantum5** [comment]
I don't think a label field is really a good idea. Do you really want to reorder your problems and also retagging them? I think it's best if you just let the contest format choose the proper enumeration sequence.
