### ISSUE TITLE
No module named pymysql

### ISSUE THREAD

**Issue by RAJANAGORI** [DMOJ/online-judge#1160]
File "/media/mrbotcipher/VAULT/Projects/dom/site/dmoj_install_pymysql.py", line 1, in <module>
    import pymysql
ImportError: No module named pymysql

**Comment by TheAvidDev** [comment]
As per the code in `manage.py`, you need to install either `pymysql` or `MySQLdb`. So run `pip install pymysql` or `pip install MySQLdb`.

However, the docs don't include either, instead mentioning `mysqlclient` which, at least for me, crashes when attempting to install (perhaps unrelated).
