### ISSUE TITLE
Python 3.8 Support

### ISSUE THREAD

**Issue by oznakn** [DMOJ/online-judge#1163]
According to the https://docs.python.org/3/whatsnew/3.8.html#api-and-feature-removals ```time.clock``` has been removed. https://github.com/DMOJ/online-judge/blob/775e2930d7ab66d51f5ce4291b4fcfdbd9886234/judge/bridge/judgecallback.py#L20 causes a crash in Python 3.8.

**Comment by quantum5** [comment]
Yes, that was a relic from the python 2 era. In python 3, `TIMER` should just be straight up replaced with `time.monotonic`.
