### ISSUE TITLE
newly registered user, NoReverseMatch at /admin/auth/user/8/change/

### ISSUE THREAD

**Issue by evo-debug** [DMOJ/online-judge#1172]
NoReverseMatch at /admin/auth/user/8/change/
Reverse for 'judge_profile_change' with arguments '('',)' not found. 1 pattern(s) tried: ['admin/judge\\/profile\\/(?P<object_id>.+)\\/change\\/$']

This is what I get after registering a new user, and then trying to edit the user profile in the admin console. How do I fix this?

**Comment by kiritofeng** [comment]
When you create a `User` from the site interface, its associated `Profile` is not automatically created.

You can remedy this by restarting the site, as all `User`s without a `Profile` are automatically given a blank profile upon startup.

In the future, you can use `python manage.py adduser`, which creates both user and profile.
