### ISSUE TITLE
RTE (failed intializing) verdict

### ISSUE THREAD

**Issue by MetalBall887** [DMOJ/online-judge#1257]
https://dmoj.ca/src/1977373
I also tried other problems in COCI'08 and they give the same verdict.

**Comment by kiritofeng** [comment]
Firstly, this is not an issue with the site, nor the judge.

Secondly, if you compute your memory usage, your 4 arrays use over 60 MB of memory, which exceeds the 32 MB memory limit, causing the RTE (failed initializing) verdict.

In the future, please do not report errors with problems on the Github ticket trackers, we have an internal ticket system ([dmoj.ca/tickets/](https://dmoj.ca/tickets/)) for this very purpose, or you can use the official Slack  ([slack.dmoj.ca](https://slack.dmoj.ca)).
