### ISSUE TITLE
Test data always zero count

### ISSUE THREAD

**Issue by sultonov** [DMOJ/online-judge#1343]
I have a problem with the test data settings, for some reason the judge does not see all the tests and always shows zero
![image](https://user-images.githubusercontent.com/12808537/80851360-b328aa80-8c3a-11ea-8fce-4f9a8ea4dcdd.png)

There is my test data:
![image](https://user-images.githubusercontent.com/12808537/80851400-07338f00-8c3b-11ea-8fa6-0686eb7e6b89.png)

**Comment by kiritofeng** [comment]
Can you send which commits you are on for the site and judge?

**Comment by sultonov** [comment]
For site 7f9d258c9229e29da51bd3e08a9f806fd64661ad and for judge [7aa325c062d9934f40aa78fbffdafbfe09aec67b](https://github.com/DMOJ/judge-server/commit/7aa325c062d9934f40aa78fbffdafbfe09aec67b)

**Comment by kiritofeng** [comment]
Can you see if the issue persists on the latest judge commit?

**Comment by sultonov** [comment]
Thank you, after upgrading version of judge it works!
