### ISSUE TITLE
BRIDGED_JUDGE_ADDRESS Socket not running in online-judge

### ISSUE THREAD

**Issue by dms24081999** [DMOJ/online-judge#1439]
![image](https://user-images.githubusercontent.com/25902527/84023195-488b2d00-a9a5-11ea-91c3-395cb1c720d5.png)

**Comment by Ninjaclasher** [comment]
From your screenshot, it doesn't look like you are running the bridge, only the site. Have you tried connecting a judge while running the bridge with `python manage.py runbridged`?

**Comment by dms24081999** [comment]
Yeah it worked.
Thanks for your help, Sir!
