### ISSUE TITLE
Ctrl+Enter does not work while replying to a comment

### ISSUE THREAD

**Issue by ehhthing** [DMOJ/online-judge#1456]
When replying to a comment and using the 'ctrl-enter' shortcut to submit the form, no comment body is submitted. (returns `Invalid comment body.`)

Note that this does not happen when not replying to another comment.

Likely cased by #1363

**Comment by Ninjaclasher** [comment]
The issue here is that the Ctrl-Enter is binded to the `New comment` form, and not the current replying form, as the `Invalid comment body` shows on the new comment form.
