### ISSUE TITLE
Sorting by problem name does not work

### ISSUE THREAD

**Issue by Ninjaclasher** [DMOJ/online-judge#1461]
This seems to be a regression from 158fa06babd1f2c853598578ec703d6693404f5f. Since `i18n_name` is coalesced in Python now, [filtering by `i18n_name`](https://github.com/DMOJ/online-judge/blob/master/judge/views/problem.py#L307) will result in filtering by a blank field if there is no `i18n_name`.

Note that this issue is different than #1445, since any fix with adding a secondary order will simply sort by that secondary order directly (since the primary `i18n_name` order is blank).

Reproduction link: https://dmoj.ca/problems/?order=name

**Comment by kiritofeng** [comment]
Fixed by 2e85bfcd7853fb8eb762e906c730c65d4f1aadc6.
