### ISSUE TITLE
"Hide problems I've solved" Setting Does Not Work

### ISSUE THREAD

**Issue by ComputerGenius152** [DMOJ/online-judge#1472]
The "hide problems I've solved" checkbox on user pages does not actually have any effect on the problems displayed.

Steps to reproduce:
- Go to the problem page of a user which has problems you've solved
- Select the box and wait for it to automatically reload
![image](https://user-images.githubusercontent.com/31290848/85638308-906fac80-b653-11ea-9811-d4b891745e84.png)

**Comment by Xyene** [comment]
That checkbox relates to the problems displayed below it, not the table above it.

**Comment by ComputerGenius152** [comment]
I was unaware, sorry about that.
