### ISSUE TITLE
Extend new user comment mute to tickets and profile editing

### ISSUE THREAD

**Issue by kiritofeng** [DMOJ/online-judge#1487]
Users should be required to solve at least one problem before they can create tickets outside of live contests and edit their profile to discourage spam.

**Comment by Harry7557558** [comment]
Agreed. And users should be required to solve some problems before they can vote comments. It may be a good idea to allow people to see `[upvote count]/[downvote count]` when the mouse hover comment vote count area (HTML title) and display a comment tab on users' public profiles that list of all of the user's comments. Users with low average comment quality should be warned by email and be automatically muted for continued low-quality posts. Also, users should not be able to vote themselves' comments. To prevent spam voting comments, there should be an option to turn off a user's right to vote.

**Comment by TheAvidDev** [comment]
> And users should be required to solve some problems before they can vote comments.

This should be a separate issue.

> It may be a good idea to allow people to see [upvote count]/[downvote count] when the mouse hover comment vote count area (HTML title).

Ditto. I don't think this is really necessary, but it probably wouldn't be that hard to add.

> Users with low average comment quality should be warned by email and be automatically muted for continued low-quality posts.

Disagree. Emailing users is simply unnecessary for comments that others dislike. Being muted for having comments that people dislike also seems quite harsh and an easy system to abuse. Muting should be done manually, as it is.

> To prevent spam voting comments, there should be an option to turn off a user's right to vote.

If this is to be done, it should probably just be a part of the `profile.mute` field. Not really sure if this is a good or bad idea though.

> Users should be able to see the time a comment is edited.

Separate issue. This I can get behind.

---

You should probably create a separate issue for all of these potential enhancements and use the bulleted list markdown.

**Comment by Ninjaclasher** [comment]
To add on,

> And users should be required to solve some problems before they can vote comments.

This is [already implemented](https://github.com/DMOJ/online-judge/blob/master/judge/views/comment.py#L35).

> display a comment tab on users' public profiles that list of all of the user's comments.

#73

**Comment by kiritofeng** [comment]
Implemented by #1633 and #1639.
