### ISSUE TITLE
Sort User List by Username

### ISSUE THREAD

**Issue by ComputerGenius152** [DMOJ/online-judge#1522]
Allow the [list of users](https://dmoj.ca/users/) to be sorted by their usernames.

**Comment by kiritofeng** [comment]
But...why?

**Comment by ComputerGenius152** [comment]
It just feels weird to me that [as far as I know] in every table with at least one sortable field, you can sort by all the fields _except_ username.

**Comment by kiritofeng** [comment]
Understandable, but why would you want to be able to sort by username? It feels like an unnecessary feature.

**Comment by ComputerGenius152** [comment]
Personally I think seeing all the users in alphabetical order could be interesting, and there could be other uses for this as well. But I think ultimately, the main purpose of this would be consistency.

**Comment by kiritofeng** [comment]
Consensus between myself, @quantum5 and @Xyene is NACK. While the consistency is nice, we don't feel like that's a strong enough argument for adding this feature.
