### ISSUE TITLE
Submission lists should be sorted by date

### ISSUE THREAD

**Issue by Xyene** [DMOJ/online-judge#1526]
Currently, they are sorted by whatever the database engine decides (seems to be ID), but IDs are not guaranteed to be in chronological order (indeed, on dmoj.ca they no longer are, after importing PEG submissions).

**Comment by kiritofeng** [comment]
> MariaDB sucks ~ @Xyene, 2021

**Comment by Riolku** [comment]
Why was this closed: #1527 never did seem to get merged. Did it get patched?

**Comment by kiritofeng** [comment]
> Why was this closed: #1527 never did seem to get merged. Did it get patched?

It's unusably slow.

**Comment by Riolku** [comment]
Do we need an index on `date`?

**Comment by quantum5** [comment]
> Do we need an index on `date`?

:laughing: There already is one and it doesn't help. We actually have too many of them, most of them useless...
