### ISSUE TITLE
Rendering long LaTeX expressions causes page to shift

### ISSUE THREAD

**Issue by kevinjycui** [DMOJ/online-judge#1539]
Since LaTeX expressions cannot wrap, it starts going outside the page and eventually shifts the rest of the page with it. This is even more evident on smaller screens/zooming in.

### To replicate
 * Go to a problem with a particular long LaTeX rendering such as [https://dmoj.ca/problem/ccc09j1](https://dmoj.ca/problem/ccc09j1)
 * Zoom in until the LaTeX starts going out of the page

There does not exist a public example of this, but if a LaTeX expression is long enough, it will shift the rest of the text as so:
![image](https://user-images.githubusercontent.com/38621453/93692180-cb9c4300-fabd-11ea-8c06-df60f0576fab.png)

**Comment by TheAvidDev** [comment]
You can also shrink your browser window (such as in the case of a vertical problem) and you can see the issue on the problem you linked.

**Comment by int-y1** [comment]
I could not reproduce this in Chrome and Firefox. Does this issue still exist?

![Capture](https://user-images.githubusercontent.com/14223529/164381023-7108b1e5-dacd-4681-aa7a-d3410525829e.PNG)

![Capture](https://user-images.githubusercontent.com/14223529/164381186-b5adb3c1-3c2d-4742-806f-f779f4c1deed.PNG)

**Comment by quantum5** [comment]
Probably not then. Feel free to reopen if you can still reproduce this.
