### ISSUE TITLE
Copy Button on Code Block Disappears When Going Through Comment History

### ISSUE THREAD

**Issue by PeiAllen** [DMOJ/online-judge#1541]
As you can see in the image below, 
![image](https://user-images.githubusercontent.com/32986987/94033238-c1649800-fd8e-11ea-9d16-c84b467e8a1b.png)
the copy button on code blocks disappears when you go into a comment's revision history. 
This bug stays even if you go back into the most recent version and is fixed by reloading the page. 
Reproduction can be attempted at https://dmoj.ca/problem/graph2p1#comment-13359.

**Comment by Xyene** [comment]
Adding the copy button is currently done in JavaScript, on page load. It should be added on insertion of a code block (i.e. via a mutation observer) as well.
