### ISSUE TITLE
Counting issue with submisssions throughout the year 

### ISSUE THREAD

**Issue by JackyTruong** [DMOJ/online-judge#1570]
![DMOJ bug](https://user-images.githubusercontent.com/41493012/96468708-66418c00-11fa-11eb-8d3a-1a5e6165210e.PNG)
![Bug Pt2](https://user-images.githubusercontent.com/41493012/96468716-66da2280-11fa-11eb-838c-94049d2cfa6e.PNG)
Not sure why, but the submission was not counted on that day, though I still got the points and completion for the problem. My DMOJ is Lynthical if you need to see it.

**Comment by Ninjaclasher** [comment]
This is due to timezone differences. 8:16PM October 16 is really October 17 UTC, so it is counted as an October 17 submission.

FWIW, this is also how Github does it.

**Comment by JackyTruong** [comment]
Ah okay

**Comment by JackyTruong** [comment]
Ah okay
