### ISSUE TITLE
When live updating submissions list, don't create new submission row until after Ajax call

### ISSUE THREAD

**Issue by Ninjaclasher** [DMOJ/online-judge#1598]
Currently, when live updating, if there is a new submission, we first [append the new row and hide it](https://github.com/DMOJ/online-judge/blob/master/templates/submission/list.html#L158). The row only becomes visible after the following Ajax call. If the Ajax call takes a while, it leads to the following visual bug (occurs on both Chrome and Firefox):
![image](https://user-images.githubusercontent.com/29607503/108156325-71280280-70ae-11eb-8d5b-7efb17c2ada4.png)
Note: the top border of the list is not visible.

We should probably change it so that the new row is only created once the Ajax call finishes (in the `.done` section). This also fixes the following two issues:
 - There is a period of time when there are only 49 submissions on the list (after the bottom submission is removed and before the top submission becomes visible).
 - If the Ajax call fails, the submission list will become shorter and shorter since the bottom submission gets removed but the top submission never becomes visible.

**Comment by Ninjaclasher** [comment]
For whoever implements this, one thing to note is that moving the row creation into the `.done` could result in some submissions being "swapped". Consider the scenario:
1. Submission 1 is received, and `update_submission` is called. The Ajax request is sent.
2. Submission 2 is received, and `update_submission` is called. The Ajax request is sent.
3. Submission 2's Ajax request comes back, and `.done` is called for submission 2. Submission 2's row gets attached to the submission list.
4. Submission 1's Ajax request comes back, and `.done` is called for submission 1. Submission 1's row gets attached to the submission list _after_ submission 2.

This will need to be tested.

**Comment by quantum5** [comment]
Can we just use a CSS `:empty` selector to fix this?
