### ISSUE TITLE
Add disallowed characters statement validator

### ISSUE THREAD

**Issue by Xyene** [DMOJ/online-judge#1612]
We should add a `DMOJ_PROBLEM_STATEMENT_DISALLOWED_CHARACTERS = ('“', '”', '‘', '’') ` settings option, and validate (at least) problem statements to not contain any of the characters within it.

We've tried the social solution, but it's proven hard to enforce.

**Comment by YashKumarVerma** [comment]
sounds like valid addition. I'd like to work on it. I understand what needs to be done, but could you explain the `We've tried the social solution, but it's proven hard to enforce.` a bit ?

**Comment by Xyene** [comment]
The social solution was/is simply asking problemsetters to not use those characters in their problems. However, Google Docs inserts them by default, and I believe Mac OS X does so too. We've occasionally slipped up and let a problem with magic quotes through.

Banning magic quotes may seem arbitrary, but we've had cases in the past where problemsetters unknowingly introduced magic quotes into their sample input descriptions, where they really meant the ASCII versions. Contestants then copy/pasted the sample input, and became very confused when their programs crashed.
