### ISSUE TITLE
Sort users by ratings by default on leaderboards

### ISSUE THREAD

**Issue by AnonymousNautilus** [DMOJ/online-judge#1617]
Currently, users on leaderboards are ranked by points by default. Problem-based points are not accurate representations of a user's performance, due to some users only do problem types that they are good at; due to overrated/underrated problems; due to users rely on outside help or passing high-point problems using improper ways, etc.

Compare to points, contest-based rating is a more accurate representation of a user's competitive programming performance. The ability to solve problems independently within a time limit better represents a user's programming skill. Since most rated contests are well-organized with plagiarism checkers and strict rules to discourage cheating, it is fairer to use contest performance to represent a user's performance.

I think DMOJ can rank users by ratings by default on site and organization leaderboards; display contest information before problem solved information to encourage users to compete for ratings instead of points. A majority of online judge platforms (including Codeforces) do this. Problem-based points may be used to represent the performance of unrated users or to break the tie when multiple users have the same rating.

**Comment by kiritofeng** [comment]
This is a social problem that requires social solutions, not technical ones.
