### ISSUE TITLE
Web push notification for contest clarifications

### ISSUE THREAD

**Issue by cuom1999** [DMOJ/online-judge#1641]
Does DMOJ support web push notification when a clarification added during a contest? Something like CF contests with web alerts and notifications.

**Comment by Ninjaclasher** [comment]
See #56.

**Comment by cuom1999** [comment]
If I read it correctly, the system has not supported live updates yet, hasn't it?

**Comment by Xyene** [comment]
Super late reply, but that's right. Closing this as a duplicate of #56 though; patches of course welcome to add live update support :slightly_smiling_face:
