### ISSUE TITLE
User rating not updated if contest floor/ceil rating is changed.

### ISSUE THREAD

**Issue by cuom1999** [DMOJ/online-judge#1696]
Suppose we have user **A** who has rating of 1500 attending a contest. We initially rate the contest with no ceiling or floor. **A** then gets a new rating of 1700. After that, we want to rerate the contest with floor = 1600. 

Expected: **A** will be not rated in this contest because his last rating = 1500 < 1600. His rating after this should be 1500.
Reality: **A** will be not rated but his rating will still be 1700.

The problem may lie in these lines. We only update ratings for `users` who satisfy the conditions. Other users should be rerolled to their `last_rating`. 

https://github.com/DMOJ/online-judge/blob/7d9914b9a57296345fd27f5e688bc64b7139eb5e/judge/ratings.py#L137-L142

**Comment by kiritofeng** [comment]
Can you confirm that you are on the latest commit? This sounds very similar to  #1684.

I do not believe that code snippet tells the whole story: iirc contests should be rated by calling its rate function:
https://github.com/DMOJ/online-judge/blob/7d9914b9a57296345fd27f5e688bc64b7139eb5e/judge/models/contest.py#L385
which clears the previous ratings.

**Comment by cuom1999** [comment]
It clears the Rating objects, but not updated users' ratings. When I go to user **A** profile page, I don't see his rating chart. However, his rating still displays 1700.
