### ISSUE TITLE
How to create a welcome message on the homepage?

### ISSUE THREAD

**Issue by yang6wolf** [DMOJ/online-judge#1705]
I have successfully deployed DMOJ. 
But I don't know how to create the welcome message on the homepage.

<img width="1342" alt="截屏2021-06-02 上午12 07 09" src="https://user-images.githubusercontent.com/34153578/120356113-93c8e900-c336-11eb-9625-347a4ae2cb4f.png">

I noticed that this information is related to the login status. 
It is displayed normally when there is no login status, and is hidden after login.

This feature is very useful, but it took a few hours and it was not set up successfully.

**Comment by fluix-dev** [comment]
It's the `home_page_top` key in Miscellaneous Configurations. See https://github.com/DMOJ/docs/issues/4

**Comment by yang6wolf** [comment]
The problem has been solved. 

Thank you very much~ @fluix-dev

**Comment by fluix-dev** [comment]
No problem, please close the issue.
