### ISSUE TITLE
Fix unstyled `li` on /stats/language

### ISSUE THREAD

**Issue by kiritofeng** [DMOJ/online-judge#1756]
![image](https://user-images.githubusercontent.com/15059063/130880894-09b4f390-4bba-4c0b-bd87-08fa7b54c953.png)
The `Language` link is missing its CSS

**Comment by int-y1** [comment]
Is wrapping it in a `<ul>` acceptable?

![Capture](https://user-images.githubusercontent.com/14223529/135935377-c282583b-d88c-4961-88a0-a6caab8f7cb7.png)

**Comment by Ninjaclasher** [comment]
I would recommend looking at how tabs are implemented for other pages:
 - https://github.com/DMOJ/online-judge/blob/master/templates/problem/list.html#L167
 - https://github.com/DMOJ/online-judge/blob/master/templates/tabs-base.html
 - https://github.com/DMOJ/online-judge/blob/master/templates/problem/problem-list-tabs.html

**Comment by Dongheon97** [comment]
To fix this problem, I push my branch and pull request.
Please, check [https://github.com/DMOJ/online-judge/pull/1822](url)
