### ISSUE TITLE
Update Mathjax to v3

### ISSUE THREAD

**Issue by ehhthing** [DMOJ/online-judge#1760]
We should upgrade to Mathjax v3, since v2 is no longer actively developed and for enhanced security.

**Comment by int-y1** [comment]
DMOJ is currently on MathJax 2.7.5 so it is worthwhile to search for `2.7.5`.

Upgrading instructions: https://docs.mathjax.org/en/latest/upgrading/v2.html

After MathJax is upgraded, go to `Edit profile` > `Math engine` and check if any options need to be changed.
