### ISSUE TITLE
Convert django.conf.urls.url to django.conf.urls.(re_)path

### ISSUE THREAD

**Issue by quantum5** [DMOJ/online-judge#1791]
Let's switch to the less confusing `django.conf.urls.path` and make future copy-paste produce better code. For stuff actually needing regular expressions, we should use `django.conf.urls.re_path`.

In fact, `django.conf.urls.url` is deprecated in Django 3.1 and will be removed in 4.x.

**Comment by jisoochoi7561** [comment]
I'm new to open source. May I work on this issue?

**Comment by kiritofeng** [comment]
1823 has been merged.
