### ISSUE TITLE
Infer "Private to organizations" problem admin field from length of "Organizations"

### ISSUE THREAD

**Issue by Xyene** [DMOJ/online-judge#1829]
This would make the interaction between the two less confusing. "Private to organizations" can be updated at model save time.

**Comment by Riolku** [comment]
Out of curiosity, could we remove the booleans entirely? I can PR this.

**Comment by kiritofeng** [comment]
> Out of curiosity, could we remove the booleans entirely? I can PR this.

No: grabbing the list of joinable contests is done by iterating the contests, and checking `organizations.exists()` is ~10x slower than checking `is_organization_private`.
