### ISSUE TITLE
unable to load resources

### ISSUE THREAD

**Issue by thecodersatish** [DMOJ/online-judge#1833]
while running the online judge using nginx im getting following error log please help me on this

**Comment by thecodersatish** [comment]
2021/12/22 08:03:19 [emerg] 16457#16457: invalid number of arguments in "root" directive in /etc/nginx/sites-enable
d/default:41
2021/12/22 08:06:41 [notice] 16472#16472: signal process started
2021/12/22 08:06:45 [error] 16473#16473: *2 directory index of "/home/thecodersatish/site/resources/icons/" is forb
idden, client: 157.47.49.84, server: <hostname>, request: "GET / HTTP/1.1", host: "34.125.242.206"
2021/12/22 08:06:47 [error] 16473#16473: *2 open() "/usr/share/nginx/html/static/cache/css/output.67d014bf30e2.css"
 failed (2: No such file or directory), client: 157.47.49.84, server: <hostname>, request: "GET /static/cache/css/o
utput.67d014bf30e2.css HTTP/1.1", host: "34.125.242.206", referrer: "http://34.125.242.206/"
2021/12/22 08:06:47 [error] 16473#16473: *1 open() "/usr/share/nginx/html/static/cache/js/output.6721e5112e7a.js" f
ailed (2: No such file or directory), client: 157.47.49.84, server: <hostname>, request: "GET /static/cache/js/outp
ut.6721e5112e7a.js HTTP/1.1", host: "34.125.242.206", referrer: "http://34.125.242.206/"
2021/12/22 08:06:47 [error] 16473#16473: *1 open() "/usr/share/nginx/html/static/icons/logo.svg" failed (2: No such
 file or directory), client: 157.47.49.84, server: <hostname>, request: "GET /static/icons/logo.svg HTTP/1.1", host
: "34.125.242.206", referrer: "http://34.125.242.206/"
2021/12/22 08:06:48 [error] 16473#16473: *1 open() "/usr/share/nginx/html/static/icons/logo.png" failed (2: No such
 file or directory), client: 157.47.49.84, server: <hostname>, request: "GET /static/icons/logo.png HTTP/1.1", host
: "34.125.242.206", referrer: "http://34.125.242.206/"

**Comment by fluix-dev** [comment]
Did you edit [this line](https://github.com/DMOJ/docs/blob/master/sample_files/nginx.conf#L41) from the sample NGINX config? It looks like it's incorrect based on the below:

```
2021/12/22 08:03:19 [emerg] 16457#16457: invalid number of arguments in "root" directive in /etc/nginx/sites-enabled/default:41
```

I *think* it should be `root /home/thecodersatish/site` based on your other logs.

**Comment by thecodersatish** [comment]
Thank you. My issue resolved
