### ISSUE TITLE
How to add new page

### ISSUE THREAD

**Issue by thecodersatish** [DMOJ/online-judge#1837]
Could you please tell me how can i add a new page in site

**Comment by kiritofeng** [comment]
Are you referring to flatpages? There's an option in the admin sidebar for that.

**Comment by thecodersatish** [comment]
No I want to add a dynamic page

**Comment by kiritofeng** [comment]
Register it in [urls.py](https://github.com/DMOJ/online-judge/blob/master/dmoj/urls.py) and write the associated view and templates.
