### ISSUE TITLE
Increase Precision on Relative Time Offsets

### ISSUE THREAD

**Issue by Riolku** [DMOJ/online-judge#1846]
On things like contests and submissions, relative times are given. Unfortunately, they aren't that precise. "2 hours ago" can mean anything from 1:30 to 2:30.

I was going to PR this, but it seems that the library in use, [Moment.js](https://momentjs.com) has no real good solution. We use `fromNow()`, here's the [relevant documentation](https://momentjs.com/docs/#/displaying/fromnow/).

What can be done? Would we find another library? Would we try to hack moment.js? What other options do we have?

**Comment by int-y1** [comment]
What about the built-in `Intl.RelativeTimeFormat.prototype.format()`? [reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/format)

If the browser doesn't support it (e.g. IE11), just display the absolute time.
