### ISSUE TITLE
Two factor authentication code not working 

### ISSUE THREAD

**Issue by aayushbest** [DMOJ/online-judge#1913]
Hi my account username is aayushbest.
I am using Microsoft Authenticator for my two factor authentication code on dmoj.ca.
But suddenly it stopped working.
It says that my code is invalid.
Sharing the picture that contains my mobile authenticator and two factor website side by side
![signal-2022-03-28-084810](https://user-images.githubusercontent.com/34985919/161393474-a9313ab7-7943-45e1-bfa8-755131ba4aa2.jpeg)
Please help me with this issue otherwise my hardwork would be lost without any mistake from my end.
Thanks in advance!
.

**Comment by kiritofeng** [comment]
1. I'm not sure you understand the point of a 2FA token: it is to be an extra layer of entropy on top of your password, and as such, should never be shared.
2. Building on the previous point, the point of 2FA is to ensure that an attacker cannot compromise your account. None of the administrative staff have any way of verifying, to our satisfaction, that you are in fact the owner of this account, and not an attacker trying to gain access, having compromised the account's email and sending us pictures of a fabricated 2FA key. This is the very purpose of 2FA.
3. This is for issues with the codebase, not for dealing with your inability to log in. Unless you have a reasonable suspicion that this is an error with the codebase, I will be closing this ticket.
