### ISSUE TITLE
May I request to delete an account?

### ISSUE THREAD

**Issue by KhaosWulf** [DMOJ/online-judge#1914]
In the middle of working on a problem, I already had my main account, but had to create another one when my login wouldn't work. I was on a time crunch, couldn't remember the password, and made another account. I've since been able to get back into my main account, but wanted to ask if I can request the other account to be deleted, so all of my submissions are just in one area? I can also let you know what email to deactivate, for that second newer account.

**Comment by ehhthing** [comment]
Please email contact@dmoj.ca, GitHub issues are for technical issues with the DMOJ codebase.

**Comment by KhaosWulf** [comment]
> Please email [contact@dmoj.ca](mailto:contact@dmoj.ca), GitHub issues are for technical issues with the DMOJ codebase.

Ah, I apologize. Thank you very much.
