### ISSUE TITLE
TypeError when starting server

### ISSUE THREAD

**Issue by lequocbinh04** [DMOJ/online-judge#1935]
After installing follow the instructions here: https://docs.dmoj.ca/#/site/installation

I try to run the server with the command `python3 manage.py runserver 0.0.0.0:8000` and try to access it and get the following error. How to fix it?

![image](https://user-images.githubusercontent.com/68278027/168851495-1e6a0681-2966-43b2-8d9f-14d75076be11.png)

**Comment by int-y1** [comment]
In the meantime, you can fix this error by downgrading Pygments. `pip3 install pygments==2.11.2`
