### ISSUE TITLE
'NoneType' object has no attribute 'isoformat'

### ISSUE THREAD

**Issue by hieupham1103** [DMOJ/online-judge#1965]
'NoneType' object has no attribute 'isoformat' in **/site/judge/views/user.py**
```
        context['submission_data'] = mark_safe(json.dumps({
            date_counts['date_only'].isoformat(): date_counts['cnt'] for date_counts in submissions …
        }))
```

**Comment by Ninjaclasher** [comment]
You must [load timezone info into mariadb](https://mariadb.com/kb/en/mysql_tzinfo_to_sql/).

**Comment by hieupham1103** [comment]
> You must [load timezone info into mariadb](https://mariadb.com/kb/en/mysql_tzinfo_to_sql/).
oh it work
