### ISSUE TITLE
Greek Localization does not get merged to master

### ISSUE THREAD

**Issue by ptheoch** [DMOJ/online-judge#1968]
Hello!
We have been waiting patiently since end of March for our contribution (Greek Localization of 100% of the site) ([#1893](https://github.com/DMOJ/online-judge/pull/1893)) to be merged to master, but we keep seeing it blocked ([#1891](https://github.com/DMOJ/online-judge/pull/1891))..
Could someone please proceed with the merge?
Thanks in advance!

**Comment by kiritofeng** [comment]
Greek translation has been merged.

**Comment by Xyene** [comment]
Thanks for the contribution!
