### ISSUE TITLE
After clicking on Abort or reloading the page displays the result(AJAX/Event ISSUE)

### ISSUE THREAD

**Issue by kumarshubham01** [DMOJ/online-judge#1975]
judge completes its task still result not get update to the site results only get visible if we reload the site or click on the Abort Button
![Screenshot from 2022-07-20 17-24-15](https://user-images.githubusercontent.com/84670623/179976753-a4aa277c-5f53-4298-a1bb-651e69835389.png)
it will keep waiting until we don't click on abort or reload the page 

![Screenshot from 2022-07-20 17-24-23](https://user-images.githubusercontent.com/84670623/179977038-f5599970-a469-433c-b846-bd28979e704a.png)

As we can see But as soon as possible if we click on abort or reload the page we got our result

**Comment by Xyene** [comment]
This sounds like the event server hasn't been set up (or has been set up incorrectly), so the site cannot push out live updates to clients.
