### ISSUE TITLE
How the source code is receiving and executing them?

### ISSUE THREAD

**Issue by Miltonbhowmick** [DMOJ/online-judge#1989]
Hi,
Very good learning repository for making OJ. I am newbie at this project. Can someone tell me how this DMOJ receiving source code from client end after click on `submit` button and execute the `submitted code` in view function and send response json?

Thanks in Advance

**Comment by Xyene** [comment]
Please join [the Discord](https://discordapp.com/invite/EgJVpxz) for these sorts of questions, this issue tracker is for bugs and feature requests.
