### ISSUE TITLE
Allow Changing Emails

### ISSUE THREAD

**Issue by Riolku** [DMOJ/online-judge#1996]
Currently, we have users email an admin email to change their email. We could, and really, should, automate this process, by sending a verification to both emails... Or maybe just the new one?

We should consider a case where a user has lost access to their old email but still has access to their account through, say, their password. Do we want to support that as a common case or should we fall back to emailing?

**Comment by Riolku** [comment]
Related (ish) #1707

**Comment by quantum5** [comment]
We should just resend the initial confirmation email to the new email and send a notification to the old email that something was changed.
