### ISSUE TITLE
License iframe doesn't render

### ISSUE THREAD

**Issue by Balint-R** [DMOJ/online-judge#1997]
For example, https://dmoj.ca/license/cc-by-nc-sa-3.0 is currently displayed as 
![image](https://user-images.githubusercontent.com/76824890/190826617-f26a6152-5d47-416e-bf46-4e5b4caff79f.png)
https://github.com/DMOJ/online-judge/pull/1959 might be relevant.

**Comment by quantum5** [comment]
The fact that it used `<iframe>`s to display a licence is basically abusing an unintended "feature" and we should put the full licence text in there...

**Comment by int-y1** [comment]
There's a markdown version at https://github.com/idleberg/Creative-Commons-Markdown/blob/main/3.0/by-nc-sa.markdown

**Comment by Xyene** [comment]
Updated https://dmoj.ca/license/cc-by-nc-sa-3.0 accordingly, thanks.

**Comment by Xyene** [comment]
https://dmoj.ca/license/fdl1.3 has also been updated, so this is now complete.
