### ISSUE TITLE
Feature request: disable comments within problems (all at once)

### ISSUE THREAD

**Issue by FherStk** [DMOJ/online-judge#2046]
Dear DMOJ team,

I would like to disable the comments along the entire site, but I couldn't be able to find any option for that. I'm using a self-hosted DMOJ instance to teach programming to my students, and I don't want them to post a problem solution within a comment, otherwise they get used to copy/paste instead of solving by themselves. 

I know I can disable comments problem by problem, but could be nice to disable them all in once.

Thanks in advance and kind regards,
Fher

**Comment by Xyene** [comment]
There is no built-in support for this, but you should be able to patch out comments in your install by deleting

https://github.com/DMOJ/online-judge/blob/1b68ed36b6c88507cca0dbe16259b230167453bf/templates/problem/problem.html#L326

**Comment by Xyene** [comment]
While we don't quite have the time resources to maintain a large matrix of options other than what we run on <https://dmoj.ca>, it should be pretty easy to maintain this in a fairly pain-free way on your end.

I recommend keeping a directory of diff files that are applied every time you update, something similar in spirit to:

```bash
git reset origin/master --hard
git pull origin master

for f in patches/*; do
    patch -p1 < "$f"
done
```

We do something like this on <https://dmoj.ca> for anything that isn't quite suitable to be merged upstream.

**Comment by FherStk** [comment]
Thanks again 😊
