### ISSUE TITLE
How to import problems into DMOJ?

### ISSUE THREAD

**Issue by Algortex** [DMOJ/online-judge#2047]
Hi,
I'd like to ask on how to import problems into DMOJ.
I have problems in a format known as FPS (freeproblemset).

Please find the link to my problemset below.
https://github.com/zhblue/freeproblemset

Is there any method to batch-import problemset into DMOJ (in any format)?

**Comment by kiritofeng** [comment]
Short answer: no.

Longer answer: you can probably(?) modify https://github.com/DMOJ/online-judge/blob/master/judge/management/commands/create_problem.py to parse your problem format and add it to the set, while also generating the [init.yml](https://docs.dmoj.ca/#/problem_format/problem_format?id=inityml). Then you can batch upload the resultant `init.yml` and the testcases to the judges. If you have enough problems with custom graders, you may wish to consider writing a `contrib` module for them in the judge (see https://github.com/DMOJ/judge-server/blob/master/dmoj/contrib/testlib.py for an example that tries to deal with `testlib` and https://github.com/DMOJ/judge-server/tree/master/testsuite/testlib_partial for an example of how to use it).

**Comment by Algortex** [comment]
This would be a very good feature suggestion for DMOJ devs

**Comment by Algortex** [comment]
> This would be a very good feature suggestion for DMOJ devs

Why not?

**Comment by Riolku** [comment]
With a range of possible formats, it makes little sense to write, test, and maintain code for an operation that will be done only once. Most likely, it is better to take the above suggestion and write a one-off script, and I would suggest that anybody encountering this specific problem in the future do the same.

If there is a specific format you want to support, over multiple DMOJ instances, for some reason, feel free to create, publish, and maintain your own code that eases importing of problems. 

DMOJ devs are unpaid volunteers. Personally, if a feature doesn't interest me, or doesn't widely benefit the community, I won't implement it. Furthermore, understand that any code in this repository is a maintenance burden for us. We have to test and maintain it. For a feature we will never use, that's simply not worth our time.

**Comment by Algortex** [comment]
> With a range of possible formats, it makes little sense to write, test, and maintain code for an operation that will be done only once. Most likely, it is better to take the above suggestion and write a one-off script, and I would suggest that anybody encountering this specific problem in the future do the same.
> 
> If there is a specific format you want to support, over multiple DMOJ instances, for some reason, feel free to create, publish, and maintain your own code that eases importing of problems.
> 
> DMOJ devs are unpaid volunteers. Personally, if a feature doesn't interest me, or doesn't widely benefit the community, I won't implement it. Furthermore, understand that any code in this repository is a maintenance burden for us. We have to test and maintain it. For a feature we will never use, that's simply not worth our time.

OK, was just trying to say that batch importing of IOI and codeforces problems into DMOJ would be a nice feature, was not asking for devs to implement it
