### ISSUE TITLE
Question: Your output (clipped)

### ISSUE THREAD

**Issue by FherStk** [DMOJ/online-judge#2057]
Dear DMOJ team,

Is there an easy way to disable the clipped output or to display something like "your output vs expected output" as HackerRank does? If there's nothing implemented about it, please, if you could me point in the correct direction about what to change in the source code, I would appreciate it.

Thanks again for your time and kindness,
Fher

**Comment by Xyene** [comment]
To disable clipped output, set `output_prefix_len: 0` in `init.yml`. See https://github.com/DMOJ/judge-server/blob/master/dmoj/problem.py#L209 for defaults of that and other settings.

For "your output vs expected output", you'll probably want to define a new checker that provides what info you want as part of `extended_feedback` (see https://github.com/DMOJ/judge-server/blob/91328ad1507f782d7cee65b48fd2951328f56a07/dmoj/checkers/linecount.py for inspiration)>

**Comment by FherStk** [comment]
Thanks a lot!
I've applied output_prefix_length: 25165824 in order to display the complete output.

**Comment by Xyene** [comment]
Great! Though I'd be careful with that setting, I suspect a submission just doing `while (1) printf("aaaaaaa");` will hang your database with a prefix that long.
