### ISSUE TITLE
Markdown not working on static pages

### ISSUE THREAD

**Issue by FherStk** [DMOJ/online-judge#2058]
Dear DMOJ team,

I'm trying to create a DMOJ tutorial for my colleagues using the static pages, but I found that the markdown is not working. Should I perform some additional steps or configurations?

Thanks in advance,
Fher

**Comment by Xyene** [comment]
You need to select the `markdown` or `markdown_math` flatpage template: https://github.com/DMOJ/online-judge/tree/master/templates/flatpages

**Comment by FherStk** [comment]
Great! Thanks again!
