### ISSUE TITLE
500 - invalid_state when registering a new account

### ISSUE THREAD

**Issue by emladevops** [DMOJ/online-judge#2059]
![Screenshot from 2022-12-13 20-33-27](https://user-images.githubusercontent.com/80335335/207336314-a4a2aaa8-7fc1-4710-84dc-bab968b6e379.png)

I got this problem when trying to register for a new account,
But something went wrong after I press on register, it actually respond with a SIGSEGV state, I still can receive email to activate my account by the way.

What's wrong with this?

**Comment by kiritofeng** [comment]
Can you please provide the stack trace?

**Comment by emladevops** [comment]
![Screenshot from 2022-12-13 20-59-07](https://user-images.githubusercontent.com/80335335/207350922-adc32db5-a5c4-48c9-949e-fb57b50c0a2c.png)

Thank you very much <3

**Comment by emladevops** [comment]
I'm not pretty sure where the log is stored by the way. Can you help me with that?

**Comment by emladevops** [comment]
Btw, I'm using runserver with manage.py

**Comment by emladevops** [comment]
2022/12/14 11:11:41 [error] 1535#1535: *18 "/root/online-judge/resources/icons/accounts/register/index.html" is forbidden (13: Permission denied), client: 162.158.178.42, server: oj.csoj.tech, request: "GET /accounts/register/ HTTP/1.1", host: "oj.csoj.tech"

So I tried to run with nginx, supervisor and I got this error

**Comment by kiritofeng** [comment]
I don't think that's the error. If you're having trouble locating the logs, you can temporarily set `DEBUG=True`, reproduce the error, copy out the log, and the **set `DEBUG` back to `False`**.

**Comment by emladevops** [comment]
![image](https://user-images.githubusercontent.com/80335335/207774606-7b4ce477-a8ae-4a45-9813-05ad52b7d342.png)
I got this error, it seems like that I got a ValueError

**Comment by emladevops** [comment]
I've also picked up a PDF file and set `DEBUG=False`, you can take a look at it.
[ValueError at _accounts_register_.pdf](https://github.com/DMOJ/online-judge/files/10233789/ValueError.at._accounts_register_.pdf)

**Comment by emladevops** [comment]
[ValueError at _accounts_register_.pdf](https://github.com/DMOJ/online-judge/files/10233793/ValueError.at._accounts_register_.pdf)
Here's the error

**Comment by emladevops** [comment]
Alright, so I fixed the problem by myself, so this is a fix for everyone who got the same problem
You'll actually have to fix your database, since something is messed up badly, I tried to rebuild the DB and it worked out just fine.
Thanks <3
