### ISSUE TITLE
Private contest for classes not working

### ISSUE THREAD

**Issue by FherStk** [DMOJ/online-judge#2060]
Dear DMOJ team,

I'm setting up a contest with the following config:
- Private for organization (it's open to join).
- Private for class (I have 3 classes with access code).

First issue:
- The request to join a class displays just the request message, which must be manually approved. I cannot find where to join using the access code.

Second issue:
- The contest is being displayed for everyone within the organization despite the class (the user is not enrolled in any class, just in the organization).

Thanks again for your help and support,
Fher

**Comment by quantum5** [comment]
1. Joining classes by access code is not currently implemented. I'll add it soon.
2. For a contest to be visible to a single class, nothing should be added to the list of organizations with access. Can you try it without any organization on the contest, just classes?

**Comment by FherStk** [comment]
Hi,

1. Thanks, it will be great :)
2. This is the behavior:
* Contest visible + organization + class:
   * User belongs to organization + class -> can see the contest.
   * User belongs to organization (only) -> can see the contest.

* Contest visible + organization only:
  * User belongs to organization + class -> can see the contest.
  * User belongs to organization (only) -> can see the contest.

* Contest visible + class only:
  * User belongs to organization + class -> can see the contest.
  * User belongs to organization (only) -> can see the contest.

Thanks again for your help,
Fher

**Comment by quantum5** [comment]
For the contest visibility issue, this seems to be a regression introduced by #1830. It should be fixed in #2065. After patching it in, you'll need to remove all the classes, save the contest, then add them back for it to take effect. Sorry for the inconvenience.

**Comment by FherStk** [comment]
> For the contest visibility issue, this seems to be a regression introduced by #1830. It should be fixed in #2065. After patching it in, you'll need to remove all the classes, save the contest, then add them back for it to take effect. Sorry for the inconvenience.

Hi there,

With "remove all the classes" you mean remove those from the contest or remove entirely from the system?

Thanks again for your time,
Fher

**Comment by quantum5** [comment]
> With "remove all the classes" you mean remove those from the contest or remove entirely from the system?

Remove from contest is sufficient.

**Comment by FherStk** [comment]
Hi,

I tried again and this is the behavior I got:

Contest with organization only + user with organization and class: user can see the contest.
Contest with organization and class + user with organization and class: user can see the contest.
Contest with class only + user with organization and class: user **can't** see the contest.

Contest with organization only + user with organization only: user can see the contest.
Contest with organization and class + user with organization only: user can see the contest.
Contest with class only + user with organization: user **can't** see the contest.

I accepted or rejected the request to join the class in order to test the behavior, but the contest was always visible event when no class was setup for the user. What am I missing?

Thanks again and happy new year!
Fher

**Comment by FherStk** [comment]
**Update:**
Contest with class only + user with organization and class: this user can see the contest (users within the same organization, but different class, can't). 

I was approving the join requests through the back-office but doesn't work, it only works using the front-end (which link I didn't know). This issue is related with #2354 

Kind regards,
Fer
