### ISSUE TITLE
403 Forbidden with PDF file

### ISSUE THREAD

**Issue by emladevops** [DMOJ/online-judge#2061]
![image](https://user-images.githubusercontent.com/80335335/207594069-08a5dd66-ccb9-4ccb-9a26-9f3f92324d94.png)
Hey there, everybody.

I wrote a new problem, tried to upload a PDF file to the platform, with runserver it worked fine, but when I migrated to nginx, supervisor, I got this problem when I try to load a PDF problem

Thanks <3

**Comment by Xyene** [comment]
I'm not sure what you mean by uploading a PDF to the platform. This is not functionality we provide.
