### ISSUE TITLE
I cannot upload images 

### ISSUE THREAD

**Issue by FherStk** [DMOJ/online-judge#2075]
Dear DMOJ team,

I'm not able to upload images into my problem statements, I get a /martor/image_name.png, but I guess that the image is not being uploaded anywhere. Any clue about what I'm doing wrong? I guess I haven't setup something correctly...

Thanks in advance and have a nice Christmas Eve :)
Fher

**Comment by quantum5** [comment]
You need to configure [`MEDIA_ROOT`](https://docs.djangoproject.com/en/3.2/ref/settings/#std-setting-MEDIA_ROOT) in django and set up your webserver to serve the directory under whatever `MEDIA_URL` is set to.

**Comment by FherStk** [comment]
Great, it's working now :)

Thanks again and have nice holidays :)
