### ISSUE TITLE
SIGSEGV: invalid_state

### ISSUE THREAD

**Issue by emladevops** [DMOJ/online-judge#2076]
I got this issue when I register for a new account
![image](https://user-images.githubusercontent.com/80335335/209455087-88db9941-d08d-41e9-9a53-d397b293ee7e.png)
The activation email still went through just fine.
Not sure what's wrong, it was fine yesterday.

Thanks and regards

**Comment by emladevops** [comment]
![image](https://user-images.githubusercontent.com/80335335/209455476-68fa751f-4b56-4cde-a444-3f83e58599c8.png)
This happened if I run the server with 
```bash
python3 manage.py runserver 0.0.0.0:80 --insecure
```

**Comment by emladevops** [comment]
![image](https://user-images.githubusercontent.com/80335335/209455880-61c94331-674c-45fb-aab5-aabb55e9f2e5.png)
With DEBUG=True, I got this

**Comment by Ninjaclasher** [comment]
You likely set up the newsletter service incorrectly. Please reopen with more detailed logs if you need assistance in resolving this.
