### ISSUE TITLE
Solution template

### ISSUE THREAD

**Issue by FherStk** [DMOJ/online-judge#2095]
Dear DMOJ team,

I would like to display a solution template when the user is going to send a solution. I found some mentions to solution templates within the source code and a "solution" space within the problem editor, but I'm not sure how does it work.

I would like to show a template like this:
![image](https://user-images.githubusercontent.com/324326/210223245-0f304196-3a15-4dbb-b7bc-682a033fbcb3.png)

Is this possible, or should I implement it?

Thanks again and happy new year!
Fher

**Comment by Xyene** [comment]
There exists "language templates" within the language model admin. We do not support per-problem templates.

**Comment by FherStk** [comment]
Great! A general template per language is enough for our needs.

Thanks again :)
Fher
