### ISSUE TITLE
WYSIWYG editor not being displayed

### ISSUE THREAD

**Issue by FherStk** [DMOJ/online-judge#2123]
Dear DMOJ team,

I'm not sure why, but my ticket reporting page is not displaying the WYSIWYG editor.

What I see:
![image](https://user-images.githubusercontent.com/324326/211636109-efaf6678-eab5-49b8-8bf5-a364ac3404e8.png)

How should be:
![image](https://user-images.githubusercontent.com/324326/211636148-7e1a644d-56c1-4da5-889b-09cde306abfa.png)

I guess I should setup something, but I'm not sure what...
Any clues, please?

Thanks in advance and best regards,
Fher

**Comment by FherStk** [comment]
Hi,

Any ideas? Should I install some extra dependencies with pip or is something I haven't configured properly?

Thanks again,
Fher

**Comment by Riolku** [comment]
Odd. Have you had any other CSS oddities on the site? Did you follow the instructions on `docs.dmoj.ca`?

**Comment by FherStk** [comment]
Nope, I have no other CSS or additions on my site; and yes, I followed the instructions step by step on docs.dmoj.ca. I suspect that I've missed some requirement related with an WMD editor, but I'm not sure which one...  

I will perform some test in my testing environment.

**Comment by FherStk** [comment]
Hi again,

I'm missing something, but I cannot find it... I reinstalled all the dependencies (and also manually the `django-pagedown` component), I cleaned and collected again all the statics, etc... but nothing worked.

I have some resources not being served, but I don't know why because the files exists in their respective folders:

**Testing environment (it works):**
![image](https://user-images.githubusercontent.com/324326/216311996-e2834215-9123-4bd2-acd4-88a01dd21b07.png)

**Production environment (it fails):**
![image](https://user-images.githubusercontent.com/324326/216312201-baa76b06-82c9-43d3-a4ec-e84f35481fb4.png)

Comparing the resources, some files are missing:
* pagedown-widget.scss
* featherlight.scss
* dmmd-preview.scss
* vars-common.scss

All this files exists on both environments (production and test) but, on productions, some additional css files are generated for the missing files, which make me suspect about them, but I also tried removing those extra files with no changes:

**Testing environment (it works):**
![image](https://user-images.githubusercontent.com/324326/216313009-e2dd51bc-71f3-4ff9-a75e-fecea08ceb33.png)

**Production environment (it fails):**
![image](https://user-images.githubusercontent.com/324326/216312903-f091da99-3296-4aea-9e8a-0e14c3f7bead.png)

I'll appreciate any help or clues, thanks in advance.
Fher

**Comment by WallE256** [comment]
Hi Fher,

Maybe a few clues to debug this might be:
1. Look in the network requests on that page, and see if the site cannot pull any particular files, that might help to narrow it down.
2. Missing scss files is not a problem as those are compiled by the make_styles script into css files, which you actually need in the static folder. Make sure to run make_styles when you update, to update the built styles.

**Comment by FherStk** [comment]
Great! There was no network error when pulling resources, but running the make_styles.sh and refreshing the browser catch did the trick. Thanks a lot, you saved my day!
