### ISSUE TITLE
Low contrast in edit profile page in dark mode

### ISSUE THREAD

**Issue by notsweting** [DMOJ/online-judge#2148]
Part of #2035.

Text on edit profile page has low contrast in comparison to background colour. 

![image](https://user-images.githubusercontent.com/50222844/216773002-20a7121e-1da7-421d-9e4b-52990e558493.png)

**Comment by Ninjaclasher** [comment]
For issues related to dark mode, please add a comment to #2035 instead of making a new issue entirely.

**Comment by notsweting** [comment]
Noted, do you want me to delete + move this to #2035 as a comment or can I leave it here this time?
