### ISSUE TITLE
Align table headers to match their contents

### ISSUE THREAD

**Issue by Xyene** [DMOJ/online-judge#2159]
### Current
![image](https://user-images.githubusercontent.com/1403503/216842519-ccf7a659-ef9e-4d73-a46b-a538b91d532a.png)

### Proposed
![image](https://user-images.githubusercontent.com/1403503/216842514-957114ca-1ff3-4755-9715-0461d5a97635.png)

**Comment by Ninjaclasher** [comment]
This is done.
