### ISSUE TITLE
Tables sometimes escape page on mobile

### ISSUE THREAD

**Issue by Xyene** [DMOJ/online-judge#2207]
![Screenshot_20230218-151508](https://user-images.githubusercontent.com/1403503/219892372-8cdda420-5de5-4592-ab5c-6a53bad3619c.png)

We should just overflow with a scrollbar in this case.

**Comment by ShyamGadde** [comment]
Hello,

I recently stumbled upon this open-source project and I'm excited to get involved. I'm new to the project and open-source development in general, but I found this issue like a good place for me to start.

I was wondering if you could provide me with some guidance on how to get started with this issue. I'm a bit confused about how to set up the development environment, as I was not able to do so on Codespaces.

Additionally, I'm wondering if it would be possible for me to be assigned this issue. I'm eager to contribute to the project and I believe this issue would be a good fit for my current level of experience.
