### ISSUE TITLE
site.conf ?

### ISSUE THREAD

**Issue by duongnotnhan** [DMOJ/online-judge#2266]
![image](https://github.com/DMOJ/online-judge/assets/98535924/f3e4b418-6ed9-4267-b558-d566e29ad802)

*** Starting uWSGI 2.0.21 (64bit) on [Wed Jul  5 10:00:44 2023] ***
compiled with version: 11.3.0 on 05 July 2023 02:35:07
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: DuongNhanAC
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/duongnhanac/online-judge
writing pidfile to /tmp/dmoj-site.pid
open("/tmp/dmoj-site.pid"): Permission denied [core/utils.c line 3624]

**Comment by flitzcore** [comment]
I have the same issue. How do you solve it?

**Comment by Ahmed-Bhouri** [comment]
Hello I am Having the same problem
did you find a solution @duongnotnhan ?
