### ISSUE TITLE
I can't access into Rated Users profile

### ISSUE THREAD

**Issue by duongnotnhan** [DMOJ/online-judge#2273]
SIGSEGV: invalid_state
trang lỗi /user/QioCas
site: fatal signal: Segmentation fault
site died (signal 500, exit -11)

panic: [go back](javascript:history.back())

I have Rate 3 users and I can't enter all of 3 users's profile
/user/<Rated user>

**Comment by Ninjaclasher** [comment]
Please join the [Discord server](https://discordapp.com/invite/EgJVpxz) for help on setup. This does not seem like a bug with the code.
