### ISSUE TITLE
Upgrade to Django 4.2 LTS

### ISSUE THREAD

**Issue by int-y1** [DMOJ/online-judge#2322]
Extended support for Django 3.2 is ending in April 2024.

#1649 is back.

**Comment by Ninjaclasher** [comment]
Things to do:
- [ ] Run https://github.com/adamchainz/django-upgrade
- [ ] `s/ugettext_lazy/gettext_lazy`, `s/ifequal/if` https://github.com/DMOJ/dmoj-wpadmin
- [ ] Merge in upstream changes in https://github.com/DMOJ/martor
- [ ] Bump https://github.com/etianen/django-reversion (quick testing suggests 5.0 works without any changes)
- [ ] (Hard) Fix https://github.com/DMOJ/online-judge/blob/master/judge/utils/raw_sql.py

**Comment by Ninjaclasher** [comment]
Remaining tasks:
- [ ] Fix django-pagedown
- [ ] Re-do all changes in https://github.com/DMOJ/martor with upstream.
