### ISSUE TITLE
Missing Hindi language for translation

### ISSUE THREAD

**Issue by Git-Harshit** [DMOJ/online-judge#2331]
I see a select few languages available for some translations at [translate.dmoj.ca](https://translate.dmoj.ca/), and there's no option to add a new language. Among the available languages, I do not see Hindi as an available language for translation. Being a bi-lingual that knows Hindi (as native language) and English, I will be happy to see its translation availability and may even like to translate content to Hindi language if it could be supported in this project.

Had the discussions tab been enabled in the repo, I wouldn't be raising it as an issue here, but since it isn't available right now, I am raising this as an issue similar to #655. Kindly label it using "discussion".

Please support it by enabling this translation from its [Crowdin project](https://support.crowdin.com/changing-target-languages/). 
Also suggest if there's any way for translation volunteers to add support for any language via committing some directory structure to this repository or any other way around?

**Comment by Xyene** [comment]
Hi @Git-Harshit -- apologies for getting around to this so late, but I've enabled Hindi for translation on Crowdin. Thanks for the interest in translating!

>  Also suggest if there's any way for translation volunteers to add support for any language via committing some directory structure to this repository or any other way around?

I think we just need to click some buttons on the Crowdin end.
