### ISSUE TITLE
Managing join requests only works on front-end

### ISSUE THREAD

**Issue by FherStk** [DMOJ/online-judge#2354]
Dear team,

Managing join requests works properly front the front-end (the user is added to the organization and the class):
![imagen](https://github.com/user-attachments/assets/ef2aff78-ad51-4118-9076-be9aaa45aa0f)

But does nothing from the back-end:
![imagen](https://github.com/user-attachments/assets/2c03903e-02fa-4a5c-b6f8-6092afaa4b38)

It would be more clarifying if this works from both sides. 

Thanks a lot for all your work and effort, I love DMOJ!

**Comment by kiritofeng** [comment]
Closed by #2365.
