### ISSUE TITLE
Disqualify contest participation button

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/online-judge#313]
Would be on admin page, sets score for the problem to 0, contest score to -9999, recalculates contest score, ban user from submitting to that problem ever again, exclude user from ratings for a contest, and re-rates contest. It might be better to split this functionality into two buttons: Disqualify-submission and Disqualify-user.

**Comment by Xyene** [comment]
This is not a task that we've had to perform more than once or twice since this ticket was made.

**Comment by Xyene** [comment]
...how wrong I was. 10 disqualifications later (the most amusing was when the user joined the contest again and resubmitted his solutions), I'm very open to this idea.

Suggested implementation is a `is_disqualified` `BooleanField` in `ContestParticipation`. These participations would be shown in a shameful red at the bottom of the contest ranking list.

**Comment by BinAccel** [comment]
This should also be added to problems, since I for one am tired of first banning and then playing policeman with submissions
