### ISSUE TITLE
Disallow batch deleting User/Profile/Problem/Contest models

### ISSUE THREAD

**Issue by Xyene** [DMOJ/online-judge#335]
Yes, there is a confirmation dialog, but when "Delete selected users" is right next to "Rescore users", it is perfectly plausible that a tired admin could get past the confirmation view by reflex. There's really no need to batch delete such important models: in almost two years of running DMOJ, I don't think we've ever batch-deleted anything but submissions.

**Comment by quantum5** [comment]
I usually batch delete objects after a search instead of clicking into every single page.
