### ISSUE TITLE
Simple Solution to the RabbitMQ Question

### ISSUE THREAD

**Issue by quantum5** [DMOJ/online-judge#399]
We can easily implement a highly flexible submission queue pop with MySQL without any schema changes:

``` sql
UPDATE judge_submission SET judged_on_id = ? WHERE judged_on_id IS NULL AND status = 'QU' ORDER BY id ASC LIMIT 1;
SELECT id FROM judge_submission WHERE status = 'QU' AND judged_on_id = ? ORDER BY id ASC LIMIT 1;
```

We simply have to ensure every QU submission have `judged_on` = `None`. Then we can use either `event_socket_server`, which magically works, write a fully async `node.js` bridge server to handle submissions, or perhaps use something else like `Twisted`? This would be 100% scalable instead of relying on a process local queue, and not have any of the dispatching trouble that RabbitMQ has. What could possibly go wrong?

**Comment by quantum5** [comment]
The above SQL code does not consider the case that a bridge dies. To solve this, an extra bridge_id can be added, and each bridge assigned an unique id. Alternatively, this can be a `ForeignKey`.

```sql
UPDATE judge_submission SET judged_on_id = ?, bridge_id = ? WHERE judged_on_id IS NULL AND bridge_id IS NULL AND status = 'QU' ORDER BY id ASC LIMIT 1;
SELECT id FROM judge_submission WHERE status = 'QU' AND judged_on_id = ? AND bridge_id = ? ORDER BY id ASC LIMIT 1;
```

If a bridge dies, the submission will stop at exactly where it is without any hazard, should a judge attempt to authenticate against a different bridge. Otherwise massive chaos will ensue when a submission is set against that judge and still `QU`. On bridge startup, all submissions assigned to that bridge that have not reach completion must obviously have been still grading while the bridge went down, and need to be marked `IE`.

**Comment by quantum5** [comment]
Very obviously, more constraints will have to be set on the `UPDATE` query to ensure the submission modified is the one that the current judge can grade.

It is also necessary to consider the case of a judge being connected to another bridge, that is capable of handling the submission. In such a distributed scenario, both bridges must be signalled to ensure such submission is judged.

**Comment by Xyene** [comment]
Superseded by a lot of other work.
