### ISSUE TITLE
Option to download user submission data

### ISSUE THREAD

**Issue by Xyene** [DMOJ/online-judge#40]
Though unlikely, it is possible that we may at any time lose portions of our database to unforeseen bugs. Or that we may be asked by regional contest organizers to remove their problems from the DMOJ if/when they develop their own OJ (funding et al.)

When this happens, it would be highly inconvenient to those who have submitted those problems to have to visit each problem and save their source. In general, a backup feature located on the users page would be useful in the long run.

It would operate with two options: `Backup all` and `Backup best`. Based on the option, a zip/tar file would be generated and the user would be able to download it. Very convenient!

This feature could be extended to include a `Download` option on submission pages.

**Comment by quantum5** [comment]
I afraid backing up all subs will be very expensive. Generating a large file and downloading it screws Django over very hard. Translation: the entire thread is blocked. Better would be to use nginx to deliver the file, but no one cleans it up. May be an hourly cron to delete files older than 24 hours could do the job. The user would also be barred from requesting another backup within 24 hours to save our resources.

**Comment by quantum5** [comment]
Depending on the size, we could use django to generate, or we could use [`uwsgi`'s mules](http://uwsgi-docs.readthedocs.org/en/latest/Mules.html) as slaves for this purpose. It seems to fit the current setup nicely.

**Comment by Xyene** [comment]
This would remains a feature that would be nice to have, especially since many users like to upload their solutions onto Github, etc.
