### ISSUE TITLE
Migration squashing

### ISSUE THREAD

**Issue by quantum5** [DMOJ/online-judge#437]
This issue will track migration squashing. But we must first answer the question: how often should we squash all our migrations? Every 50? Every 100? Every 200?

Documentation: https://docs.djangoproject.com/en/stable/topics/migrations/#squashing-migrations

This is obviously low priority.

/cc @Xyene

**Comment by Xyene** [comment]
Every 50 sounds fine, right now we're over 60 and it is noticeably slow even on a fast server.

**Comment by quantum5** [comment]
You realize that _you_ will have to write part of the squashed migration, right? Django isn't smart enough to drop all the transition stuff we have.

**Comment by Xyene** [comment]
Mhm, which is why it remains a low priority.

**Comment by quantum5** [comment]
From Django 2.0 release notes:

> The `on_delete` argument for `ForeignKey` and `OneToOneField` is now required in models and migrations. Consider squashing migrations so that you have fewer of them to update.

We better do this.

**Comment by Xyene** [comment]
We did this. We might do this again someday, but let's close this issue out for now.
