### ISSUE TITLE
Adding fullscreen to admin page

### ISSUE THREAD

**Issue by kiritofeng** [DMOJ/online-judge#471]
Can the fullscreen button from submissions to problems be added to the markup "editor" on the admin page?
## Button:

![Button](https://dl.dropboxusercontent.com/u/62637212/DMOJ%20Stuff/Here.PNG)
## Editor:

![Editor](https://dl.dropboxusercontent.com/u/62637212/DMOJ%20Stuff/Button.PNG)

**Comment by quantum5** [comment]
Idea: have a tabbed write/preview interface like GitHub in full screen mode.

**Comment by kiritofeng** [comment]
Tabbed editor was added.
