### ISSUE TITLE
Problem Types can be picked up by the API

### ISSUE THREAD

**Issue by Phoenix1369** [DMOJ/online-judge#483]
Relevant for problems which are part of a live contest as participants can discover the tags during the competition.

**Comment by BinAccel** [comment]
Users can also leave a contest and look at the problems, which circumvents this.

**Comment by quantum5** [comment]
The change here does not work when the contest is over, since it bans you from seeing the types after the contest is over.

On the other hand, after reworking the upsolving system in #473, leaving the contest would not be a problem.
