### ISSUE TITLE
API rework

### ISSUE THREAD

**Issue by Xyene** [DMOJ/online-judge#506]
The API was implemented as a spur-of-the-moment thing years ago, and it definitely needs a redesign. First off, the current iteration does not play nice with auto-querystring formatting that most web APIs offer. Apart from that, it's also missing a lot of data.

I propose we add a `/api/v2/` API using proper design principles, then shim the current `/api/` with the v2 API.

**Comment by quantum5** [comment]
I don't see why you would need to shim it, since the current API code can just be kept. It is less complicated than a shim as is.

**Comment by Xyene** [comment]
This is complete.
