### ISSUE TITLE
Contest listing displays "Join" where it should say "Spectate"

### ISSUE THREAD

**Issue by hnrgu** [DMOJ/online-judge#544]
Contest listing displays "Join" even after finishing contest.
![](https://i.imgur.com/YRXNe9a.png)

Clicking on the "Join" button results in an alert.
![](https://i.imgur.com/qyA5MSe.png)

**Comment by BinAccel** [comment]
This is because the code in `site/templates/contest/list.jade` is different from that in `site/templates/contest/contest-tabs.jade`

**Comment by quantum5** [comment]
Wow @kiritofeng are you anywhere near finishing this?

**Comment by Carson-Tang** [comment]
The change from #1272 did not fix the issue as contest.is_in_contest checks whether the user is currently participating in the contest rather than if the user has participated.
