### ISSUE TITLE
Allow trusted users to add problems

### ISSUE THREAD

**Issue by Xyene** [DMOJ/online-judge#546]
The idea behind this would be to allow users with a certain PP and/or contest rating to add problems without admin supervision. User-added problems would appear in their own list, in a separate tab. From there good problems could be voted on, and eventually be approved by admins to join main problems listing.

Obviously, a number of things need to happen before this is viable.

* [ ] #545 - allowing users to vote on problems
* [x] #327 - ticket system
* [x] #467 - site managed data
* [x] judge rewrite to make judge errors "clean", i.e. have no possibility of hanging
    * obvious exception would be custom graders etc., which would be outside the scope of what regular users would be allowed to add

**Comment by quantum5** [comment]
I think a per-user disk quota would be nice, just in case someone uploads 10GB of test data.

**Comment by Xyene** [comment]
Yeah, I think this might've been discussed as part of #467, though it's definitely necessary.

**Comment by Xyene** [comment]
This should also be a threshold-based thing where once you pass it, we set a boolean field in your profile. This way we can enable it for users who don't meet the PP reqs, but are trusted (e.g. teachers).

**Comment by Xyene** [comment]
Generators have no possibility of hanging after https://github.com/DMOJ/judge/issues/295, since they are sandboxed.

**Comment by Xyene** [comment]
This has basically been implemented. It's not fully integrated with the site and there's some amount of Discord discussion that goes on, but it's been working out well.
