### ISSUE TITLE
Redesign registration email

### ISSUE THREAD

**Issue by Xyene** [DMOJ/online-judge#560]
Needs a whole lotta love.

![image](https://cloud.githubusercontent.com/assets/1403503/23337143/60a54276-fbb2-11e6-9754-7653d3029e46.png)

**Comment by Xyene** [comment]
The TLE email would be a good start.

**Comment by BinAccel** [comment]
Why does it say `on the !`

**Comment by Xyene** [comment]
_Now_ you're asking the right questions.

**Comment by Xyene** [comment]
This is embarrassingly bad. Even a plaintext email would be better, honestly.
