### ISSUE TITLE
Submission Lock

### ISSUE THREAD

**Issue by kiritofeng** [DMOJ/online-judge#595]
A `BooleanField` on each submission, that would prevent it from being rejudged. Should probably be applied to contest submissions post-contest (automatically?)

Would probably require two new perms as well:
- `RejudgeLockedSubmission` name is self-explanatory
- `UnlockSubmission` allows user to unlock a sub

**Comment by quantum5** [comment]
A rejudge locked submission perm is folly to the greatest extent. It is defeats the point of preventing superusers from accidentally rejudging submissions, which happens *a lot*.
