### ISSUE TITLE
edit_profile page can crash

### ISSUE THREAD

**Issue by monouno** [DMOJ/online-judge#656]
I found that the browser (Chrome\Firefox\Safari) will crash while accessing the edit profile page when the QuerySet of "organizations" is empty.
https://github.com/DMOJ/site/blob/7b5c11371d8224901c507fa0cc1ef8b2475de1dd/judge/forms.py#L59

**Comment by quantum5** [comment]
This is a problem in the JavaScript code in a third party library. The fix is to add an organization.

@Xyene an example organization should be created by our default fixtures to avoid this situation.

**Comment by Xyene** [comment]
An example organization is created by our fixtures; I suppose an alternative for users who don't want to have an organization (or have no need of one) is to simply not display the organization field if there are no organizations. Then, the JS would not be loaded to cause problems.
