### ISSUE TITLE
Option to hide scoreboard until participation ends

### ISSUE THREAD

**Issue by Xyene** [DMOJ/online-judge#665]
Would be useful for more accurately simulating contests like the CCC.

This could be as simple as a `BooleanField` in the `Contest` model, with a bit of logic in the contest list and contest tabs on whether to show rankings or not.

**Comment by Xyene** [comment]
This has been implemented.

**Comment by Xyene** [comment]
Should also allow the contest organizers to see the rankings.

**Comment by Ninjaclasher** [comment]
Contest organizers have been able to see the rankings for a while now. Is there anything else that should be fixed before this issue is closed?

**Comment by Xyene** [comment]
Not that I know of, this was left open because the original implementation was pretty buggy.
