### ISSUE TITLE
submissions made in a contest where scoreboard visibility is private do not surface publicly

### ISSUE THREAD

**Issue by xiaowuc1** [DMOJ/online-judge#671]
Reproduction steps:

1) Create a contest with option "Hide scoreboard" enabled.
2) Compete in contest, solve a problem in contest.
3) Wait for contest duration to expire.

Expected outcome:
Submission is visible after contest.

Actual outcome:
Submission cannot be found after contest.

**Comment by Xyene** [comment]
For future reference, the line in question is https://github.com/DMOJ/site/blob/master/judge/views/submission.py#L197. I'm guessing the desired behavior is to have your own submissions be visible after the contest but nobody else's, until "Hide scoreboard" is disabled.
