### ISSUE TITLE
contest ranking sort does not appear to sort by the exact number of points earned by contestant

### ISSUE THREAD

**Issue by xiaowuc1** [DMOJ/online-judge#675]
Reproduction steps (copied from a production instance of this issue):

1) Generate a problem with the opportunity to get partial credit.
2) Insert the problem into a contest weighted such that the user can get a fractional number of points less than 1 in the weighting of the contest.
3) In the contest, score the number of points referenced in step 2.

Expected outcome:
This user outperforms other users who have scored zero points on the contest.

Actual outcome:
This user's ranking is strictly worse than other people who have scored zero points.

An anonymized scoreboard from production is provided showing exactly what this looks like.

<img width="202" alt="screen shot 2018-04-15 at 12 12 00 pm" src="https://user-images.githubusercontent.com/3413714/38782323-845f4952-40a6-11e8-90e8-ce05020ba065.png">

**Comment by quantum5** [comment]
Proposal: change `points` to `FloatField`, add a `points_precision` to contest config, and we round points to that many digits (default: 3). Then, we display as many decimal digits as necessary, i.e. `str(int(points)) if points == int(points) else str(points)`.
