### ISSUE TITLE
Allow problems integration from other online judge systems.

### ISSUE THREAD

**Issue by ndrwnaguib** [DMOJ/online-judge#687]
It seems like that problems' authoring can only be done through writing them in _Markdown_ and _LaTeX_, I suggest allowing integrating problems from other Online Judge systems (e.g., CodeForces, URI, SPOJ, etc.) which will be a great enhancement for authors since they would only import the problem's link (for example) after which DMOJ only start communicating with the other OJ through its API to retrieve the solution of the user.

**Comment by kiritofeng** [comment]
This is too difficult to do and rarely worth it, and would require a large time commitment to integrating other OJ's APIs and dealing with their changes.

#614 would allow for problem statements to be imported as PDFs, which solves the issue of typing up statements, and it is not that difficult to manually configure problem data in most cases.
