### ISSUE TITLE
Extension of submit button

### ISSUE THREAD

**Issue by Xyene** [DMOJ/online-judge#80]
The submission submit view Submit button could have a dropdown feature to accommodate #17 and #79; dropdown to "Submit on judge: {{ judge }}" and "Submit anonymously".

**Comment by quantum5** [comment]
Button dropdown might not work nicely when we have more than 3 judges. Anonymous would be probably be better off as a checkbox.

**Comment by FatalEagle** [comment]
Another consideration is to separate the judges into clusters, so duplicate machines only get counted once.

**Comment by Xyene** [comment]
Anonymous submission should be made at least a little bit hard to access, otherwise we'll have everyone submitting anonymously to prevent possible shame in case of WA.

**Comment by quantum5** [comment]
The mere existence of anonymous submissions will promote submitting anonymously until AC.

**Comment by FatalEagle** [comment]
Which users can already accomplish by making a smurf account.

**Comment by quantum5** [comment]
Is there any usefulness to anonymous submit other than avoiding responsibility for non-AC?

**Comment by FatalEagle** [comment]
Anonymous information would be treated equally. For example, if I saw an imaginary user named bobhob628 submit on some problem, I would probably ignore it. But if it were an anonymous user, I might just click into it.

For already registered users, it's just potential privacy against _certain people_ stalking their profiles.

**Comment by Xyene** [comment]
Its more worth to make something legal and to tax it than to have it illegal and subverted by everyone every time. If anonymous submissions were under a Codecha, it would deter users from submitting anonymously. But hopefully not enough for them to create/log into a smurf account.

**Comment by Xyene** [comment]
Selecting which judge to submit on has been available for a while. We're unlikely to add anonymous submissions at this point.
