### ISSUE TITLE
Dockerized version of the site

### ISSUE THREAD

**Issue by Maitre-Hiboux** [DMOJ/online-judge#866]
Hello,

I created for a recreational use inside my company a dockerized version of the site (and of the judge, see issue in DMOJ/judge ) that is intended to work offline behind proxies and in containers. It is not perfect at all but at least it is working and I am still working on improving it. I thought you may be interested so I came here to bring it to you.

https://github.com/Maitre-Hiboux/dmoj-site-docker

**Comment by Maitre-Hiboux** [comment]
A few precision, this version is intended to be deployed in a company (eg: behind a proxy and with a ldap authentication) but is easily adaptable to be run in normal conditions, commenting out the call to the offline.sh buildscript in the Dockerfile and not replacing the middleware.py and local_settings.py files should do the trick. Not tested however.

**Comment by Maitre-Hiboux** [comment]
Also, I'm doing a docker-compose of it all, it is working right now as long as I place the application at / (eg : www.<domain_name>/ ) but I have difficulties putting it on /dmoj/  (eg : www.<domain_name>/dmoj/ ) as I have to prefix all urls and it's not that easy. I wanted to do so in order to run thsi application along with other applications runs on other prefixes. If someone already gave a look to this problem.

**Comment by outloudvi** [comment]
We're also working on dockerizing of DMOJ [here](https://github.com/schoj/dmoj-dockercompose). It's intended to be public accessible (and hosted in China, which is the reason why it involves a lot of npm/apt/pypi mirror repositories).

On prefixing, I think it would be easier to make use of nginx's reverse proxy or something to get it working. Changing `urls.py` also works but I'm afraid there are also some urls in the HTML templates which need modifying...

**Comment by Maitre-Hiboux** [comment]
I've finished the prefixing part and made a pull request about it. Indeed I had to modify a single lien of code in template/base.html to make the navbar's url prefixed. And to add the prefix without modifying urls.py which is a bit dirty you can use a variable uwsgi_params script_name in nginx and another arg in uwsgi.ini to add your prefix to both urls and static urls.

Also I've ended up my dockerized version and made a docker-compose for it so if yo want I can also add this on a git repo.

**Comment by Maitre-Hiboux** [comment]
Also i've made some things differently from your docker compose, I've separated the db on a separate container and db and I've put a nginx reverse container that enables you to add other applications hosted on the same site ut on different urls.

**Comment by Maitre-Hiboux** [comment]
I've just put everything in a repo but haven't tested it yet, I will do so soon enough but here it is already if it can help you : 

https://github.com/Maitre-Hiboux/dmoj-docker-compose

**Comment by Maitre-Hiboux** [comment]
And beofre running it you have to manually configure the db at least once (haven't added yet the 2 conf lines specified in site/README.md in the docker-compose conf)

**Comment by outloudvi** [comment]
> Also i've made some things differently from your docker compose, I've separated the db on a separate container and db and I've put a nginx reverse container that enables you to add other applications hosted on the same site ut on different urls.
I see that. Actually seperating db and the site is better for many reasons. I just merged them together for the sake of the simplicity of deploying 😄

**Comment by Xyene** [comment]
(Very late reply, posting just for posterity and for anyone who runs across this issue in the future...)

@Ninjaclasher has been maintaining a Docker image for a few years now: https://github.com/Ninjaclasher/dmoj-docker

It's unlikely we'll have the bandwidth to maintain this upstream given we don't -- and won't -- run the site within Docker in prod, but I've heard of plenty of success stories with their image.
