### ISSUE TITLE
When adding a first solution to a problem, the shortcut for adding hyperlinks within that solution does not work

### ISSUE THREAD

**Issue by xiaowuc1** [DMOJ/online-judge#939]
Reproduction steps:

1) Find an existing problem without an editorial present.
2) Go to the admin portal to edit it.
3) Click `Add another Solution` - this should be solution 1.
4) Attempt to insert a hyperlink.

Expected behavior: You get the popup saying to paste the URL you wish to link to.

Actual behavior: Nothing happens.

**Comment by xiaowuc1** [comment]
NB: The same behavior seems to apply to all other shortcuts.

**Comment by Ninjaclasher** [comment]
I _think_ this issue is "fixed" as pagedown is no longer used as the admin site editor.

There is a related issue where the shortcuts with dropdowns do nothing for Martor, but I'm not sure if that should be a new issue or rename this issue (adding a hyperlink works fine now).

**Comment by Xyene** [comment]
Closing as per the above.
